Automatically fix EOL newlines with workflow
Also commits and pushes non-empty changes

diff --git a/.github/workflows/eof-newlines.yml b/.github/workflows/eof-newlines.yml
--- a/.github/workflows/eof-newlines.yml
+++ b/.github/workflows/eof-newlines.yml
@@ -1,23 +1,27 @@
 name: Check EOF newlines
-run-name: Checking EOF newlines
-on:
-  pull_request:
-    types: [opened, synchronize]
+
+on: [pull_request]
+
 jobs:
-  check-newlines:
+  check_newline:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y fd-find
-      - name: Check newline
-        run: |
-          set -eo pipefail
-          no_newline=$(fdfind -t f --exclude '*.{svg,ico,png,jpeg,jpg,webp}' -x sh -c 'if test -n "$(tail -c1 {})" ; then echo "{} doesn'\''t end in newline" ; fi')
-          if [ -n "$no_newline" ]; then
-              echo "Some files don't end with newline:" >&2
-              echo "$no_newline" >&2
-              exit 1
+    - name: Checkout code
+      uses: actions/checkout@main
+      with:
+        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+    - name: Install file command
+      run: sudo apt-get update && sudo apt-get install -y file
+    - name: Check for missing newline
+      run: |
+        git ls-files -z | while IFS= read -rd '' f; do
+          if file --mime-encoding "$f" | grep -qv binary; then
+            tail -c1 < "$f" | read -r _ || echo >> "$f"
           fi
+        done
+    - name: Commit & Push changes
+      uses: actions-js/push@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        message: "Worflow: Add EOF newline(s)"
